name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/vcpkg
            ./vcpkg

          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/xmake.lua') }}
      - name: install

        run: |

          brew install llvm@16

          brew install xmake

          brew install libtool automake

               

               export LDFLAGS="-L/usr/local/opt/llvm/lib"

               export CPPFLAGS="-I/usr/local/opt/llvm/include"

               

               echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile

      - name: vcpkg-action

        uses: johnwason/vcpkg-action@v4
        with:
          triplet: x64-osx-release
          pkgs: "gtest cppunit"

          token: ${{ github.token }}

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: ".xmake-cache"

      - name: make1

        run: xmake f --toolchain=llvm --sdk=/usr/local/opt/llvm/ -y -v
      - name: make2
        run: xmake build -v -y

      - name: test

        run: xmake run -v
