name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: install
              run: |
                  cd ~
                  sudo apt install -y libcppunit-dev
                  cd ~
                  git clone https://gitcode.net/mirrors/microsoft/vcpkg
                  cd vcpkg
                  sh bootstrap-vcpkg.sh
                  ~/vcpkg/vcpkg integrate install
                  ~/vcpkg/vcpkg integrate bash
                  ~/vcpkg/vcpkg install  cppunit
                  sudo add-apt-repository -y ppa:xmake-io/xmake
                  sudo apt update
                  sudo apt install -y xmake
            - name: make
              run: xmake build -v
            - name: test
              run: xmake run -v
