name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: install
              run: |
                  cd ~
                  sudo apt install -y libcppunit-dev
                  cd ~
                  git clone https://gitcode.net/mirrors/microsoft/vcpkg
                  cd vcpkg
                  sh bootstrap-vcpkg.sh
                  ~/vcpkg/vcpkg integrate install
                  ~/vcpkg/vcpkg integrate bash
                  ~/vcpkg/vcpkg install  cppunit
                  sudo add-apt-repository -y ppa:xmake-io/xmake
                  sudo apt update
                  sudo apt install -y xmake gcc-12
                  sudo rm -fv /usr/bin/gcc
                  sudo ln -s /usr/bin/gcc-12 /usr/bin/gcc
                  sudo apt install -y  g++-12
                  sudo rm -fv /usr/bin/g++
                  sudo ln -s /usr/bin/g++-12 /usr/bin/g++
            - name: make
              run: xmake build -vy
            - name: test
              run: xmake run -v
