# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: gcc

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - uses: actions/cache@v3
#       with:
#           path: |
#             C:\vcpkg
#             ./vcpkg

#           key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/xmake.lua') }}
#     - uses: actions/cache@v3
#       with:
#                   path: |
#                       C:\Users\runneradmin\AppData\Local\.xmake

#                   key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

    - name: install-gcc-13
      run: |
          wget http://kayari.org/gcc-latest/gcc-latest.deb && sudo dpkg -i gcc-latest.deb && rm gcc-latest.deb
          export PATH=/opt/gcc-latest/bin:$PATH
          export LD_RUN_PATH=/opt/gcc-latest/lib64
    

          
    - name: vcpkg-action

      uses: johnwason/vcpkg-action@v4
      with:
          triplet: x64-linux-release
          pkgs: "gtest cppunit"

          token: ${{ github.token }}

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
          xmake-version: branch@dev
          actions-cache-folder: ".xmake-cache"
    - name : release
      run: |
          xmake clean -a
          xmake f  -y -v --toolchain=gcc-13 --sdk=/opt/gcc-latest/ --mode=release
          xmake build -v -y  -w 
    - run:   xmake clean -a    
    - name: config

      run: xmake f  -y -v --toolchain=gcc-13 --sdk=/opt/gcc-latest/ --mode=test
    - name: build
      run: xmake build -v -y  -w -g test

    - name: test

      run: xmake run -v -g test
