name: llvm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runner/.xmake

          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/vcpkg
            ./vcpkg

          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/xmake.lua') }}
      - name: Install LLVM and Clang
        
        
        run: |
          export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
          export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
          export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
          export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
          export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"
          brew install llvm@16
      - name: install
        run: |
          brew install xmake python@3.11 six z3 zstd 
          brew install libtool automake
               export LDFLAGS="-L/usr/local/opt/llvm/lib"
               export CPPFLAGS="-I/usr/local/opt/llvm/include"
               echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile

      - name: vcpkg-action

        uses: johnwason/vcpkg-action@v4
        with:
          triplet: x64-osx-release
          pkgs: "gtest cppunit"

          token: ${{ github.token }}

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: ".xmake-cache"
      - name: release
        run: |
          xmake clean -a
          xmake f  -y -v --toolchain=llvm --sdk=/usr/local/opt/llvm --mode=release
          xmake build -v -y  -w
      - run: xmake clean -a
      - name: config

        run: xmake f --toolchain=llvm --sdk=/usr/local/opt/llvm -y -v --mode=test
      - name: make
        run: xmake build -v -y -w -g test

      - name: test

        run: xmake run -v -g test
