name: llvm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-llvm-16
        with:
          path: |
            /opt/homebrew/opt/llvm@16

            /usr/local/Cellar/llvm/

          key: ${{ runner.os }}-llvm-16
      - uses: actions/cache@v3
        with:
          path: |
            /Users/runner/.xmake

          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - uses: actions/cache@v3
        with:
          path: |
            /usr/local/share/vcpkg
            ./vcpkg

          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/xmake.lua') }}
      - name: Install LLVM and Clang

        if: ${{ steps.cache-llvm-16.outputs.cache-hit!= 'true' }}
        run: brew install llvm@16
      - run: export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"  
      - name: install
        run: |
          brew install xmake python@3.11 six z3 zstd 
          brew install libtool automake
               export LDFLAGS="-L/opt/homebrew/opt/llvm@16/lib"
               export CPPFLAGS="-I/opt/homebrew/opt/llvm@16/include"
               echo 'export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"' >> /Users/runner/.bash_profile

      - name: vcpkg-action

        uses: johnwason/vcpkg-action@v4
        with:
          triplet: x64-osx-release
          pkgs: "gtest cppunit"

          token: ${{ github.token }}

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
          actions-cache-folder: ".xmake-cache"
      - name: release
        run: |
          xmake clean -a
          xmake f  -y -v --toolchain=llvm --sdk=/opt/homebrew/opt/llvm@16 --mode=release
          xmake build -v -y  -w
      - run: xmake clean -a
      - name: config

        run: xmake f --toolchain=llvm --sdk=/opt/homebrew/opt/llvm@16 -y -v --mode=test
      - name: make
        run: xmake build -v -y -w -g test

      - name: test

        run: xmake run -v -g test
